docs: adds docs tool, material for mkdocs, along with more fleshed ou…
brycedrennan/imaginAIry pull request #428
Opened 2023-12-22 05:17 UTC by jaydrennan

…t docstrings.

this includes ability to serve up a local docs website.

2023-12-22 05:29 UTC, brycedrennan requested changes
Delete most the stuff chatgpt made. It highlights unimportant details.

2023-12-27 22:26 UTC, brycedrennan commented on docs/assets/000078_260972468_PLMS40_PS7.5_portrait_photo_of_a_freckled_woman.jpg
Lets make a new more interesting image and use it here.

2023-12-28 03:41 UTC, brycedrennan commented
`make docs`
```
mkdocs serve
make: mkdocs: No such file or directory
make: *** [docs] Error 1
```

2023-12-29 17:28 UTC, jaydrennan commented on docs/assets/000078_260972468_PLMS40_PS7.5_portrait_photo_of_a_freckled_woman.jpg
Replaced it with something different, but not necessarily better.

2023-12-29 17:28 UTC, jaydrennan commented
> Delete most the stuff chatgpt made. It highlights unimportant details.

I believe this has been completed.

2023-12-29 17:29 UTC, jaydrennan commented
> `make docs`
> 
> ```
> mkdocs serve
> make: mkdocs: No such file or directory
> make: *** [docs] Error 1
> ```

This is probably because I didn't add necessary pip requirements.

2024-01-02 13:56 UTC, brycedrennan commented
```
mkdocs serve
ERROR   -  Config value 'plugins': The "mkdocstrings" plugin is not installed

Aborted with 1 configuration errors!
make: *** [docs] Error 1
```

2024-01-03 04:08 UTC, jaydrennan commented
> ```
> mkdocs serve
> ERROR   -  Config value 'plugins': The "mkdocstrings" plugin is not installed
> 
> Aborted with 1 configuration errors!
> make: *** [docs] Error 1
> ```

Missed a package. They're all there now.

2024-01-05 05:35 UTC, brycedrennan approved these changes

2024-01-05 05:36 UTC, merged